### ISSUE TITLE
login, registration, authentication

### ISSUE THREAD

**Issue by DanielWilliamParsons** [Team-Strawberry-CC36/backend#49]
Firebase authentication has been added.
Once it has been checked, we can go ahead and add database queries for the following:

add new user to database on registration
get user details on login
remove session cookie on logout
In the current backend design, these tasks can be done in:

src/auth/controllers/authControllers.ts
src/auth/models/authModel.ts

**Comment by brianaqp** [comment]
@DanielWilliamParsons Good content to create more issues this morning.

**Comment by DanielWilliamParsons** [comment]
For anyone who needs this info about Firebase:

The authentication process for Firebase is as follows (as far as I understand - I could be wrong!):
**Step 1**: Login or Registration - receive a temporary token on frontend from firebase. (done)

**Step 2**: Frontend sends user info and token to our backend. (To do - I started an issue for the front end project - issue 31)

**Step 3**: On the backend, authenticate the token with firebase and receive a session cookie from firebase (done)

**Step 4**: If registering, add any user data to our database, e.g., uid. If logging in, retrieve user data from our database (**_This issue_**)

**Step 5**: Send cookie received from firebase back to the frontend, and any other data (e.g., user info from our database) (Done)

**Step 6**: Any time user makes a request, use verifySessionCookie on backend through Firebase (done), but the verifySessionCookie needs applying to the routes we need authenticating.
