### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by DanielWilliamParsons** [Team-Strawberry-CC36/backend#50]
Apologies, I put this issue in the frontend project by mistake.

I wrote firebase authentication on server side.
More work needs doing with the database/prisma, so I opened a new issue #49 : login, registration, authentication.

The branch is called user-authentication.

It is should be safe to merge as I fixed all TypeScript errors, but there may be conflicts with testing.ts. If there are conflicts, just ignore my updates because I was doing temporary fixes by commenting out code.

But everything in auth folder should be okay to merge, as well as minor changes to server.ts

**Comment by brianaqp** [comment]
I merge it. It was a great implemenation. We can make some changes in how is ordered. 

I gonna check the typescript locally.
