### ISSUE TITLE
Delete experiences triggers an error 

### ISSUE THREAD

**Issue by brianaqp** [Team-Strawberry-CC36/backend#75]
## The issue

If you try to delete an experience with helpfullness votes related, it will throw an error.

This happens because there is `votes` related to that entity. 

## The solution
For deleting a whole experience, we need to delete all the helpfulness votes related first. There is two ways of do that:

1. Using prisma queries. First remove the votes asociated, and after the experience.
2. Adding 'onCascade' in schema.prisma. This is the more easier, but the more riskier, requires further testing. What happens if also delete the users related?

**Comment by ai-n0808** [comment]
@brianaqp I made PR for this. Can you take a look?
